# Generated by Django 5.0 on 2024-03-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('prod_year', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('leather_interior', models.BooleanField(default=False)),
                ('fuel_type', models.CharField(max_length=50)),
                ('engine_volume', models.FloatField()),
                ('mileage', models.FloatField()),
                ('cylinders', models.IntegerField()),
                ('gear_box_type', models.CharField(blank=True, max_length=50)),
                ('drive_wheels', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('airbags', models.IntegerField()),
            ],
        ),
    ]
